# 7-1:
Shape of a 2D array is expressed as (x, y), where x is number of rows and y is number of columns. This array will have x*y elements. 

# 7-2:
To obtain the shape of the array we can use : `np.shape(ppm)` 
Shape of `ppm` is `(3, 4)`

# 7-3:
`values = np.zeros((3, 2), dtype=int64)`

# 7-4:

In [28]:
import numpy as np
factors = np.arange(0,8, dtype='float')
factors = np.reshape(factors, (2, 4))
factors

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

# 7-5:

In [29]:
zeros = np.zeros((3, 5))
sevens = zeros + 7
sevens

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

# 7-6:


In [35]:
value = factors[1, 2]

first_row = factors[0]

subset = factors[:, [1, 2]]

factors[0, 0:3] = factors[1, 1:]

# 7-7:

In [40]:
ppm = np.array([[ 20.80, 20.71, 21.72, 18.81],
                   [ 19.91, 18.42, 20.73, 20.32],
                   [ 17.32, 21.74, 23.19, 19.98]])

# convert ppm to ppm by dividing each element by 10e3
ppb = ppm/10e3
ppb

array([[0.00208 , 0.002071, 0.002172, 0.001881],
       [0.001991, 0.001842, 0.002073, 0.002032],
       [0.001732, 0.002174, 0.002319, 0.001998]])

# 7-8:

In [42]:
data1 = np.array([[]])
data2 = np.array([[]])

avg_between_both = 0.5 * (data1 + data2)

# 7-9:

In [43]:
data3 = ppm
# 1st way:
max_data3_1 = np.max(data3)

# 2nd way:
max_data3 = data3[0,0]
for i in range(np.shape(data3)[0]):
    for j in range(np.shape(data3)[1]):
        if j > max_data3:
            max_data3 = j

        else: 
            pass
max_data3

20.8